/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.viapost.stock.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Product service. Represents a row in the &quot;Viapost_Product&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.viapost.stock.model.impl.ProductModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.viapost.stock.model.impl.ProductImpl}.
 * </p>
 *
 * @author pif
 * @see Product
 * @see com.viapost.stock.model.impl.ProductImpl
 * @see com.viapost.stock.model.impl.ProductModelImpl
 * @generated
 */
public interface ProductModel extends BaseModel<Product> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a product model instance should use the {@link Product} interface instead.
	 */

	/**
	 * Returns the primary key of this product.
	 *
	 * @return the primary key of this product
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this product.
	 *
	 * @param primaryKey the primary key of this product
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the stock ID of this product.
	 *
	 * @return the stock ID of this product
	 */
	public long getStockId();

	/**
	 * Sets the stock ID of this product.
	 *
	 * @param stockId the stock ID of this product
	 */
	public void setStockId(long stockId);

	/**
	 * Returns the article number of this product.
	 *
	 * @return the article number of this product
	 */
	public long getArticleNumber();

	/**
	 * Sets the article number of this product.
	 *
	 * @param articleNumber the article number of this product
	 */
	public void setArticleNumber(long articleNumber);

	/**
	 * Returns the stock of this product.
	 *
	 * @return the stock of this product
	 */
	public long getStock();

	/**
	 * Sets the stock of this product.
	 *
	 * @param stock the stock of this product
	 */
	public void setStock(long stock);

	/**
	 * Returns the seuil_stock of this product.
	 *
	 * @return the seuil_stock of this product
	 */
	public long getSeuil_stock();

	/**
	 * Sets the seuil_stock of this product.
	 *
	 * @param seuil_stock the seuil_stock of this product
	 */
	public void setSeuil_stock(long seuil_stock);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Product product);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Product> toCacheModel();

	@Override
	public Product toEscapedModel();

	@Override
	public Product toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}