/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.viapost.stock.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the UserDemande service. Represents a row in the &quot;Viapost_UserDemande&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.viapost.stock.model.impl.UserDemandeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.viapost.stock.model.impl.UserDemandeImpl}.
 * </p>
 *
 * @author pif
 * @see UserDemande
 * @see com.viapost.stock.model.impl.UserDemandeImpl
 * @see com.viapost.stock.model.impl.UserDemandeModelImpl
 * @generated
 */
public interface UserDemandeModel extends BaseModel<UserDemande> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user demande model instance should use the {@link UserDemande} interface instead.
	 */

	/**
	 * Returns the primary key of this user demande.
	 *
	 * @return the primary key of this user demande
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user demande.
	 *
	 * @param primaryKey the primary key of this user demande
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the user demande ID of this user demande.
	 *
	 * @return the user demande ID of this user demande
	 */
	public long getUserDemandeId();

	/**
	 * Sets the user demande ID of this user demande.
	 *
	 * @param userDemandeId the user demande ID of this user demande
	 */
	public void setUserDemandeId(long userDemandeId);

	/**
	 * Returns the demande ID of this user demande.
	 *
	 * @return the demande ID of this user demande
	 */
	public long getDemandeId();

	/**
	 * Sets the demande ID of this user demande.
	 *
	 * @param demandeId the demande ID of this user demande
	 */
	public void setDemandeId(long demandeId);

	/**
	 * Returns the user ID of this user demande.
	 *
	 * @return the user ID of this user demande
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user demande.
	 *
	 * @param userId the user ID of this user demande
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user demande.
	 *
	 * @return the user uuid of this user demande
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this user demande.
	 *
	 * @param userUuid the user uuid of this user demande
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the company ID of this user demande.
	 *
	 * @return the company ID of this user demande
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this user demande.
	 *
	 * @param companyId the company ID of this user demande
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this user demande.
	 *
	 * @return the group ID of this user demande
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this user demande.
	 *
	 * @param groupId the group ID of this user demande
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the date of this user demande.
	 *
	 * @return the date of this user demande
	 */
	public Date getDate();

	/**
	 * Sets the date of this user demande.
	 *
	 * @param date the date of this user demande
	 */
	public void setDate(Date date);

	/**
	 * Returns the origine of this user demande.
	 *
	 * @return the origine of this user demande
	 */
	@AutoEscape
	public String getOrigine();

	/**
	 * Sets the origine of this user demande.
	 *
	 * @param origine the origine of this user demande
	 */
	public void setOrigine(String origine);

	/**
	 * Returns the article of this user demande.
	 *
	 * @return the article of this user demande
	 */
	public long getArticle();

	/**
	 * Sets the article of this user demande.
	 *
	 * @param article the article of this user demande
	 */
	public void setArticle(long article);

	/**
	 * Returns the resource primary key of this user demande.
	 *
	 * @return the resource primary key of this user demande
	 */
	public long getResourcePrimaryKey();

	/**
	 * Sets the resource primary key of this user demande.
	 *
	 * @param resourcePrimaryKey the resource primary key of this user demande
	 */
	public void setResourcePrimaryKey(long resourcePrimaryKey);

	/**
	 * Returns the title of this user demande.
	 *
	 * @return the title of this user demande
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this user demande.
	 *
	 * @param title the title of this user demande
	 */
	public void setTitle(String title);

	/**
	 * Returns the status of this user demande.
	 *
	 * @return the status of this user demande
	 */
	public int getStatus();

	/**
	 * Sets the status of this user demande.
	 *
	 * @param status the status of this user demande
	 */
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this user demande.
	 *
	 * @return the status by user ID of this user demande
	 */
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this user demande.
	 *
	 * @param statusByUserId the status by user ID of this user demande
	 */
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this user demande.
	 *
	 * @return the status by user uuid of this user demande
	 * @throws SystemException if a system exception occurred
	 */
	public String getStatusByUserUuid() throws SystemException;

	/**
	 * Sets the status by user uuid of this user demande.
	 *
	 * @param statusByUserUuid the status by user uuid of this user demande
	 */
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this user demande.
	 *
	 * @return the status by user name of this user demande
	 */
	@AutoEscape
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this user demande.
	 *
	 * @param statusByUserName the status by user name of this user demande
	 */
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status by date of this user demande.
	 *
	 * @return the status by date of this user demande
	 */
	public Date getStatusByDate();

	/**
	 * Sets the status by date of this user demande.
	 *
	 * @param statusByDate the status by date of this user demande
	 */
	public void setStatusByDate(Date statusByDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(UserDemande userDemande);

	@Override
	public int hashCode();

	@Override
	public CacheModel<UserDemande> toCacheModel();

	@Override
	public UserDemande toEscapedModel();

	@Override
	public UserDemande toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}